import { Geist, Geist_Mono } from "next/font/google";
import ProtectedRoute from "@/components/protectedRout";
import { AuthProvider } from "@/features/auth/context/authContext";
import { BarberProvider } from "@/features/barbers/context/barberContext";
import "./globals.css";
import { ServiceProvider } from "@/context/servicesContext";
import { CreateAppointmentProvider } from "@/context/createAppointmentContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProtectedRoute>
            <BarberProvider>
              <ServiceProvider>
                <CreateAppointmentProvider>
                  {children}
                </CreateAppointmentProvider>
              </ServiceProvider>
            </BarberProvider>
          </ProtectedRoute>
        </AuthProvider>
      </body>
    </html>
  );
}
